/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fsm.frontend;

import java.awt.Color;
import java.awt.Container;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author emreu
 */
public class GirisEkrani extends javax.swing.JFrame {

    /**
     * Creates new form LoginScreen
     */
    public GirisEkrani() {

        initComponents();
        setTitle("Kullanıcı Giriş Ekranı");
       
        setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelGiris = new javax.swing.JPanel();
        lblSifre = new javax.swing.JLabel();
        lblKullaniciId = new javax.swing.JLabel();
        txtKullaniciId = new javax.swing.JTextField();
        txtSifre = new javax.swing.JTextField();
        lblLoginResim = new javax.swing.JLabel();
        lblEkleResim = new javax.swing.JLabel();
        lblSifreDurum = new javax.swing.JLabel();
        btnPersonelEkle = new javax.swing.JButton();
        btnGiris = new javax.swing.JButton();
        lblidDurum = new javax.swing.JLabel();
        PanelKullaniciEkle = new javax.swing.JPanel();
        lblBilgiGiriniz = new javax.swing.JLabel();
        lblKullaniciAdiEkle = new javax.swing.JLabel();
        lblSifreEkle = new javax.swing.JLabel();
        lblAdEkle = new javax.swing.JLabel();
        lblSoyadEkle = new javax.swing.JLabel();
        lblEmailEkle = new javax.swing.JLabel();
        lblButceEkle = new javax.swing.JLabel();
        txtAdEkle = new javax.swing.JTextField();
        txtSoyadEkle = new javax.swing.JTextField();
        txtKullaniciAdiEkle = new javax.swing.JTextField();
        txtSifreEkle = new javax.swing.JTextField();
        txtEmailEkle = new javax.swing.JTextField();
        txtButceEkle = new javax.swing.JTextField();
        btnKaydet = new javax.swing.JButton();
        btnGeriEkle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        PanelGiris.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblSifre.setText("Şifre");

        lblKullaniciId.setText("Kullanıcı Id:");

        txtSifre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSifreActionPerformed(evt);
            }
        });

        lblLoginResim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aglar_proje/urunresimleri/login_icon_1.png"))); // NOI18N

        lblEkleResim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aglar_proje/urunresimleri/uye_ol.png"))); // NOI18N

        btnPersonelEkle.setText("Kullanıcı Ekle");
        btnPersonelEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonelEkleActionPerformed(evt);
            }
        });

        btnGiris.setText("Giris");
        btnGiris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGirisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelGirisLayout = new javax.swing.GroupLayout(PanelGiris);
        PanelGiris.setLayout(PanelGirisLayout);
        PanelGirisLayout.setHorizontalGroup(
            PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGirisLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelGirisLayout.createSequentialGroup()
                        .addComponent(lblLoginResim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGiris, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEkleResim)
                        .addGap(0, 0, 0)
                        .addComponent(btnPersonelEkle))
                    .addGroup(PanelGirisLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKullaniciId, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSifre, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKullaniciId, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSifre, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblidDurum, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(lblSifreDurum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 6, Short.MAX_VALUE))
        );
        PanelGirisLayout.setVerticalGroup(
            PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGirisLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblKullaniciId, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtKullaniciId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblidDurum, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSifre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSifre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblSifreDurum, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGiris)
                    .addComponent(lblLoginResim)
                    .addComponent(lblEkleResim)
                    .addComponent(btnPersonelEkle))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        getContentPane().add(PanelGiris, "card10");

        PanelKullaniciEkle.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblBilgiGiriniz.setText("Lütfen Bilgileri Uygun Şekilde Giriniz");

        lblKullaniciAdiEkle.setText("Kullanıcı Adı :");

        lblSifreEkle.setText("Şifre:");

        lblAdEkle.setText("Ad :");

        lblSoyadEkle.setText("Soyad :");

        lblEmailEkle.setText("E-Mail :");

        lblButceEkle.setText("Bütçe :");

        txtAdEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdEkleActionPerformed(evt);
            }
        });

        txtSoyadEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoyadEkleActionPerformed(evt);
            }
        });

        btnKaydet.setText("Kaydet");

        btnGeriEkle.setText("Geri");
        btnGeriEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeriEkleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelKullaniciEkleLayout = new javax.swing.GroupLayout(PanelKullaniciEkle);
        PanelKullaniciEkle.setLayout(PanelKullaniciEkleLayout);
        PanelKullaniciEkleLayout.setHorizontalGroup(
            PanelKullaniciEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKullaniciEkleLayout.createSequentialGroup()
                .addGroup(PanelKullaniciEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelKullaniciEkleLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(PanelKullaniciEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKullaniciAdiEkle)
                            .addComponent(lblEmailEkle)
                            .addComponent(lblAdEkle))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelKullaniciEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAdEkle)
                            .addComponent(txtEmailEkle, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txtKullaniciAdiEkle, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addGap(0, 0, 0)
                        .addGroup(PanelKullaniciEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelKullaniciEkleLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(PanelKullaniciEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSifreEkle)
                                    .addComponent(lblButceEkle)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelKullaniciEkleLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lblSoyadEkle)))
                        .addGap(18, 18, 18)
                        .addGroup(PanelKullaniciEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelKullaniciEkleLayout.createSequentialGroup()
                                .addComponent(txtButceEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnGeriEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtSifreEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelKullaniciEkleLayout.createSequentialGroup()
                                .addComponent(txtSoyadEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnKaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelKullaniciEkleLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(lblBilgiGiriniz)))
                .addGap(58, 58, 58))
        );
        PanelKullaniciEkleLayout.setVerticalGroup(
            PanelKullaniciEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKullaniciEkleLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblBilgiGiriniz)
                .addGap(18, 18, 18)
                .addGroup(PanelKullaniciEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdEkle)
                    .addComponent(txtAdEkle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoyadEkle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSoyadEkle)
                    .addComponent(btnKaydet))
                .addGap(18, 18, 18)
                .addGroup(PanelKullaniciEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKullaniciAdiEkle)
                    .addComponent(txtKullaniciAdiEkle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSifreEkle)
                    .addComponent(txtSifreEkle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelKullaniciEkleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailEkle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmailEkle)
                    .addComponent(txtButceEkle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblButceEkle)
                    .addComponent(btnGeriEkle))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        getContentPane().add(PanelKullaniciEkle, "card10");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPersonelEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonelEkleActionPerformed
        // TODO add your handling code here:
        this.setTitle("Kullanıcı Ekleme Ekranı");
        PanelGiris.setVisible(false);
        PanelKullaniciEkle.setVisible(true);

    }//GEN-LAST:event_btnPersonelEkleActionPerformed

    private void btnGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGirisActionPerformed

        try {
            // TODO add your handling code here:
            Pattern idDesen = Pattern.compile("[0-9]");
            Pattern sifreDesen = Pattern.compile("[0-9]");
            Matcher idYakala = idDesen.matcher(txtKullaniciId.getText());
            Matcher sifreYakala = sifreDesen.matcher(txtSifre.getText());
            if (!idYakala.find()) {

                //showMessageDialog(this, "Message", "Title", ERROR_MESSAGE);
                lblidDurum.setText("Kullanıcı id bulunmamaktadır.");

            } else {
                lblidDurum.setText("");
            }
            if (!sifreYakala.find()) {

                lblSifreDurum.setText("Şifre yanlış girilmiştir.");

            } else {
                lblSifreDurum.setText("");
            }
            String gelenId = "1234";
            String gelenSifre = "1234";
            if (gelenId.equals(txtKullaniciId.getText()) && gelenSifre.equals(txtSifre.getText())) {
                MuzayedeEkrani ft = new MuzayedeEkrani();

                ft.setVisible(true);
                this.dispose();

            } else /*if(txtTc.getText()==" " && txtPersonelNo.getText()==" ")*/ {
                JOptionPane.showMessageDialog(this, "Bilgiler Doğru Girilmemiştir..");
            }

        } catch (Exception e) {
            Logger.getLogger(GirisEkrani.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnGirisActionPerformed

    private void txtSifreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSifreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSifreActionPerformed

    private void txtAdEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdEkleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdEkleActionPerformed

    private void txtSoyadEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoyadEkleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoyadEkleActionPerformed

    private void btnGeriEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeriEkleActionPerformed
        // TODO add your handling code here:
        this.setTitle("Kullanıcı Giriş Ekranı");
        PanelKullaniciEkle.setVisible(false);
        PanelGiris.setVisible(true);
    }//GEN-LAST:event_btnGeriEkleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GirisEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GirisEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelGiris;
    public javax.swing.JPanel PanelKullaniciEkle;
    private javax.swing.JButton btnGeriEkle;
    private javax.swing.JButton btnGiris;
    private javax.swing.JButton btnKaydet;
    private javax.swing.JButton btnPersonelEkle;
    private javax.swing.JLabel lblAdEkle;
    private javax.swing.JLabel lblBilgiGiriniz;
    private javax.swing.JLabel lblButceEkle;
    private javax.swing.JLabel lblEkleResim;
    private javax.swing.JLabel lblEmailEkle;
    private javax.swing.JLabel lblKullaniciAdiEkle;
    private javax.swing.JLabel lblKullaniciId;
    private javax.swing.JLabel lblLoginResim;
    private javax.swing.JLabel lblSifre;
    private javax.swing.JLabel lblSifreDurum;
    private javax.swing.JLabel lblSifreEkle;
    private javax.swing.JLabel lblSoyadEkle;
    private javax.swing.JLabel lblidDurum;
    private javax.swing.JTextField txtAdEkle;
    private javax.swing.JTextField txtButceEkle;
    private javax.swing.JTextField txtEmailEkle;
    private javax.swing.JTextField txtKullaniciAdiEkle;
    private javax.swing.JTextField txtKullaniciId;
    private javax.swing.JTextField txtSifre;
    private javax.swing.JTextField txtSifreEkle;
    private javax.swing.JTextField txtSoyadEkle;
    // End of variables declaration//GEN-END:variables
}
