/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fsm.frontend;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author emreu
 */
public class MuzayedeEkrani extends javax.swing.JFrame {

    /**
     * Creates new form Arayuz
     */
    public MuzayedeEkrani() {
        initComponents();
        setTitle("Online Müzayede Sistemi");
        setResizable(false);
        Icon urun = new ImageIcon("C:\\Users\\emreu\\Documents\\GitHub\\Winter\\aglar_proje\\src\\aglar_proje\\urunresimleri\\images.jpg");

        lblResim.setIcon(urun);
        /*
        menuSifreGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSifreGuncelleActionPerformed(evt);
                
                SifreGuncellemeEkrani sg = new SifreGuncellemeEkrani();
                sg.setVisible(true);
                 
               

            }
        });
        
         */


 /*
        private void menuSifreGuncelleActionPerformed(java.awt.event.ActionEvent evt) {
            
        SifreGuncellemeEkrani ft = new SifreGuncellemeEkrani();

                ft.setVisible(true);
                this.dispose();
        }
       
         */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblKullaniciAdi = new javax.swing.JLabel();
        lblUrunResmi = new javax.swing.JLabel();
        cbOtomatikTeklif = new javax.swing.JCheckBox();
        txtGelenTeklif = new javax.swing.JTextField();
        btnGonder = new javax.swing.JButton();
        lblResim = new javax.swing.JLabel();
        lblTeklifVer = new javax.swing.JLabel();
        lblUrunKodu = new javax.swing.JLabel();
        lblUurunKoduGosterilen = new javax.swing.JLabel();
        lblUrunAdi = new javax.swing.JLabel();
        lblUrunAdiGosterilen = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnCikisYap = new javax.swing.JButton();
        menuBarMuzayede = new javax.swing.JMenuBar();
        menuAnaSayfa = new javax.swing.JMenu();
        menuKullaniciIslemleri = new javax.swing.JMenu();
        menuBilgiGuncelle = new javax.swing.JMenuItem();
        menuSifreGuncelle = new javax.swing.JMenuItem();
        menuUrunler = new javax.swing.JMenu();
        menuMevcutUrunler = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuKasaIslemleri = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblKullaniciAdi.setText("Ahmet AK");

        lblUrunResmi.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblUrunResmi.setText("ÜRÜN RESMİ");

        cbOtomatikTeklif.setText("Otomatik Teklif");
        cbOtomatikTeklif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOtomatikTeklifActionPerformed(evt);
            }
        });

        txtGelenTeklif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGelenTeklifActionPerformed(evt);
            }
        });

        btnGonder.setText("GÖNDER");

        lblTeklifVer.setText("Teklif Ver: ");

        lblUrunKodu.setText("Ürün Kodu:");

        lblUurunKoduGosterilen.setText("1356741");

        lblUrunAdi.setText("Ürün Adı:");

        lblUrunAdiGosterilen.setText("Tablo");

        jLabel1.setText("Başlangıç Fiyatı:");

        jLabel2.setText("3500 ₺");

        jLabel3.setText("Mevcut Fiyatı:");

        jLabel4.setText("10.250 ₺");

        jLabel5.setText("Son Teklif:");

        jLabel6.setText("Ahmet AK");

        btnCikisYap.setText("Çıkış Yap");
        btnCikisYap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCikisYapActionPerformed(evt);
            }
        });

        menuAnaSayfa.setText("Ana Sayfa");
        menuBarMuzayede.add(menuAnaSayfa);

        menuKullaniciIslemleri.setText("Kullanıcı İşlemleri");

        menuBilgiGuncelle.setText("Bilgileri Görüntüle");
        menuBilgiGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBilgiGuncelleActionPerformed(evt);
            }
        });
        menuKullaniciIslemleri.add(menuBilgiGuncelle);

        menuSifreGuncelle.setText("Şifre Güncelle");
        menuSifreGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSifreGuncelleActionPerformed(evt);
            }
        });
        menuKullaniciIslemleri.add(menuSifreGuncelle);

        menuBarMuzayede.add(menuKullaniciIslemleri);

        menuUrunler.setText("Ürünler");

        menuMevcutUrunler.setText("Mevcut Ürünler");
        menuMevcutUrunler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMevcutUrunlerActionPerformed(evt);
            }
        });
        menuUrunler.add(menuMevcutUrunler);

        jMenuItem1.setText("Satılan Ürünler");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuUrunler.add(jMenuItem1);

        menuBarMuzayede.add(menuUrunler);

        menuKasaIslemleri.setText("Kasa İşlemleri");
        menuBarMuzayede.add(menuKasaIslemleri);

        setJMenuBar(menuBarMuzayede);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTeklifVer, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtGelenTeklif, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGonder))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblUrunResmi, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(cbOtomatikTeklif, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblResim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUrunAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUrunKodu, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUrunAdiGosterilen, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUurunKoduGosterilen, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblKullaniciAdi)
                        .addGap(18, 18, 18)
                        .addComponent(btnCikisYap, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKullaniciAdi)
                    .addComponent(btnCikisYap))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUrunResmi)
                    .addComponent(cbOtomatikTeklif))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblResim, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUrunKodu)
                            .addComponent(lblUurunKoduGosterilen))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUrunAdi)
                            .addComponent(lblUrunAdiGosterilen))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGelenTeklif, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGonder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTeklifVer))
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSifreGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSifreGuncelleActionPerformed
        // TODO add your handling code here:

        SifreGuncellemeEkrani sg = new SifreGuncellemeEkrani();
        sg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuSifreGuncelleActionPerformed

    private void txtGelenTeklifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGelenTeklifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGelenTeklifActionPerformed

    private void cbOtomatikTeklifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOtomatikTeklifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbOtomatikTeklifActionPerformed

    private void menuBilgiGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBilgiGuncelleActionPerformed
        // TODO add your handling code here:

        KullaniciBilgileriEkrani kb = new KullaniciBilgileriEkrani();
        kb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuBilgiGuncelleActionPerformed

    private void menuMevcutUrunlerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMevcutUrunlerActionPerformed
        // TODO add your handling code here:
        MevcutUrunlerEkrani mek = new MevcutUrunlerEkrani();
        mek.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuMevcutUrunlerActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        SatilanUrunlerEkrani satilan  = new SatilanUrunlerEkrani();
        satilan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnCikisYapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCikisYapActionPerformed
        // TODO add your handling code here:
        GirisEkrani ge = new GirisEkrani();
        ge.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCikisYapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MuzayedeEkrani.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MuzayedeEkrani.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MuzayedeEkrani.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MuzayedeEkrani.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MuzayedeEkrani().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCikisYap;
    private javax.swing.JButton btnGonder;
    private javax.swing.JCheckBox cbOtomatikTeklif;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblKullaniciAdi;
    private javax.swing.JLabel lblResim;
    private javax.swing.JLabel lblTeklifVer;
    private javax.swing.JLabel lblUrunAdi;
    private javax.swing.JLabel lblUrunAdiGosterilen;
    private javax.swing.JLabel lblUrunKodu;
    private javax.swing.JLabel lblUrunResmi;
    private javax.swing.JLabel lblUurunKoduGosterilen;
    private javax.swing.JMenu menuAnaSayfa;
    private javax.swing.JMenuBar menuBarMuzayede;
    private javax.swing.JMenuItem menuBilgiGuncelle;
    private javax.swing.JMenu menuKasaIslemleri;
    private javax.swing.JMenu menuKullaniciIslemleri;
    private javax.swing.JMenuItem menuMevcutUrunler;
    private javax.swing.JMenuItem menuSifreGuncelle;
    private javax.swing.JMenu menuUrunler;
    private javax.swing.JTextField txtGelenTeklif;
    // End of variables declaration//GEN-END:variables
}
